version: '3'
services:
  db:
     image: mysql
     container_name: devops_db
     volumes:
       - devopswebapp_db_data:/var/lib/mysql
     restart: always
     networks:
      - overlay
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: usersdb
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin123

  devopswebapp:
    build: 
      context: .
      dockerfile: DbWebDockerfile
    depends_on:
       - db
    image: devopswebapp
    networks:
      - overlay
    container_name: devopswebapp_db
    deploy:
      replicas: 3
    ports:
      - "8181:8080"

volumes:
    devopswebapp_db_data:

networks:
  overlay:
