version: '3'
services:
  db:
     image: mysql
     volumes:
       - devopswebapp_db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: usersdb
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin123
     ports:
       - "3306:3306"
     deploy:
       placement:
         constraints: [node.role == manager]

  devopswebapp:
    depends_on:
       - db
    image: devopswebapp:2.0-stack
    environment:
       DB_HOST: "$DB_HOST"
    deploy:
      replicas: 3
    ports:
      - "8181:8080"

volumes:
    devopswebapp_db_data:
