version: '3'
services:
  db:
     image: mysql
     volumes:
       - devopswebapp_db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: usersdb
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin123

  devopswebapp:
    depends_on:
       - db
    image: venkatasykam/devopswebapp:1.0-db
    deploy:
      replicas: 3
    ports:
      - "8181:8080"

volumes:
    devopswebapp_db_data:

